# -*- coding: utf-8 -*-
"""
/***************************************************************************
 TMD
                                 A QGIS plugin
 Get Weather Today from v2.00
 Generated by Plugin Builder: http://g-sherman.github.io/Qgis-Plugin-Builder/
                             -------------------
        begin                : 2019-12-12
        copyright            : (C) 2019 by GIS4Dev
        email                : gis4developer@gmail.com
        git sha              : $Format:%H$
 ***************************************************************************/

/***************************************************************************
 *                                                                         *
 *   This program is free software; you can redistribute it and/or modify  *
 *   it under the terms of the GNU General Public License as published by  *
 *   the Free Software Foundation; either version 2 of the License, or     *
 *   (at your option) any later version.                                   *
 *                                                                         *
 ***************************************************************************/
 This script initializes the plugin, making it known to QGIS.
"""


# noinspection PyPep8Naming
def classFactory(iface):  # pylint: disable=invalid-name
    """Load TMD class from file TMD.

    :param iface: A QGIS interface instance.
    :type iface: QgsInterface
    """
    #
    from .TMD import TMD
    return TMD(iface)
